### ISSUE TITLE
Cargo.lock needs to be updated in version 1.1.2

### ISSUE THREAD

**Issue by lahwaacz** [huggingface/xet-core#342]
Hi, building hf_xet 1.1.2 from [source](https://github.com/huggingface/xet-core/archive/refs/tags/v1.1.2.tar.gz) with `maturin build --locked --release` fails:

```
    Updating crates.io index
error: the lock file /build/xet-core/src/xet-core-1.1.2/hf_xet/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error:
```

**Comment by rajatarya** [comment]
Good catch @lahwaacz ! We will clean this up in our next release. I updated the Cargo.toml for 1.1.2 through GitHub web interface without running maturin locally, so Cargo.lock wasn't updated. I will update our deployment process to make sure Cargo.lock and Cargo.toml are updated for each release.

Can you tell me more about the use case which leads to building `hf-xet` from source? Is there a platform you use that isn't supported from the binary Python whls?

**Comment by lahwaacz** [comment]
We build a package for Arch Linux: https://archlinux.org/packages/extra/x86_64/python-hf-xet/

**Comment by rajatarya** [comment]
@lahwaacz Fixed in [`hf-xet 1.1.3`](https://github.com/huggingface/xet-core/releases/tag/v1.1.3). Please verify and close this issue. Thanks for reporting it and apologies for causing it!

**Comment by lahwaacz** [comment]
@rajatarya Thanks!

**Comment by grzegorz-roboflow** [comment]
Hi @rajatarya , I started seeing cargo-related issues when installing `hf-xet` while building our images:

```
lock file version `4` was found, but this version of Cargo does not understand this lock file, perhaps Cargo needs to be updated?
```

I installed rust through `rustup` but still see this issue, is it possible to keep version `3` in cargo.lock?
