### ISSUE TITLE
Download stucks at 99%

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/xet-core#409]
```
Installing collected packages: hf_xet
Successfully installed hf_xet-1.1.5
special_tokens_map.json: 100%|████████████████████████████████████████████████████████████████| 438/438 [00:00<?, ?B/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████| 749/749 [00:00<?, ?B/s]
pytorch_model.bin.index.json: 27.1kB [00:00, 27.1MB/s]                                     | 0.00/9.98G [00:00<?, ?B/s]
llava-v1.5-7b/tokenizer.model: 100%|█████████████████████████████████████████████████| 500k/500k [00:02<00:00, 169kB/s]
open_clip_pytorch_model.bin:   0%|                                                         | 0.00/10.2G [00:00<?, ?B/s]{"timestamp":"2025-07-10T19:42:56.958840Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)) }). Retrying..."},"filename":"D:\\a\\xet-core\\xet-core\\cas_client\\src\\http_client.rs","line_number":242}      | 884k/3.54G [00:26<12:46:32, 77.0kB/s]
{"timestamp":"2025-07-10T19:42:56.959128Z","level":"WARN","fields":{"message":"Retry attempt #0. Sleeping 1.1372178s before the next attempt"},"filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\reqwest-retry-0.7.0\\src\\middleware.rs","line_number":171}
                                                                                                                       {"timestamp":"2025-07-10T19:48:18.746922Z","level":"WARN","fields":{"message":"Reqwest(reqwest::Error { kind: Request, source: hyper_util::client::legacy::Error(SendRequest, hyper::Error(Io, Os { code: 10054, kind: ConnectionReset, message: \"An existing connection was forcibly closed by the remote host.\" })) }). Retrying..."},"filename":"D:\\a\\xet-core\\xet-core\\cas_client\\src\\http_client.rs","line_number":242}                      | 90.1M/10.2G [05:54<9:56:38, 281kB/s]
{"timestamp":"2025-07-10T19:48:18.747211Z","level":"WARN","fields":{"message":"Retry attempt #0. Sleeping 150.6871ms before the next attempt"},"filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\reqwest-retry-0.7.0\\src\\middleware.rs","line_number":171}
v0Q.ckpt: 100%|███████████████████████████████████████████████████████████████████| 5.33G/5.33G [33:51<00:00, 2.62MB/s]
v0F.ckpt:  95%|███████████████████████████████████████████████████████████████▋   | 5.06G/5.33G [33:11<01:37, 2.73MB/s]
v0F.ckpt:  99%|███████████████████████████████████████████████████████████████████▏| 5.27G/5.33G [43:11<02:37, 409kB/s]
llava-v1.5-7b/pytorch_model-00001-of-000(…):  97%|███████████████████████████████▏| 9.72G/9.98G [43:21<00:07, 33.1MB/s]
llava-v1.5-7b/pytorch_model-00002-of-000(…): 100%|███████████████████████████████▉| 3.54G/3.54G [39:38<00:01, 2.23MB/s]
open_clip_pytorch_model.bin:  99%|███████████████████████████████████████████████▎| 10.0G/10.2G [43:51<00:35, 3.92MB/s]
```

**Comment by jsulz** [comment]
Hi @FurkanGozukara thank you for the report - sorry you're hitting this. 

Based on the log output it appears the connection was reset as you were downloading. Is the internet connection where this download took place stable?

Did you attempt to retry to download any of the files that were not successfully downloaded?

Also, any information you could provide about your OS/environment/network would be helpful - running these two commands and providing the output would be appreciated to help debug: 

```
huggingface-cli env
env | grep HF_XET
```

**Comment by FurkanGozukara** [comment]
@jsulz this happens on someone else one of my followers so i dont have evernything

but we use python 3.10.11 and windows 11

he tried so many times always stuck at 99% 

but when he used Warp VPN i think it worked

**Comment by jsulz** [comment]
@FurkanGozukara thanks for the additional details! 

Do you know the repository where your follower was hitting this error?

**Comment by FurkanGozukara** [comment]
> [@FurkanGozukara](https://github.com/FurkanGozukara) thanks for the additional details!
> 
> Do you know the repository where your follower was hitting this error?

sure here : https://huggingface.co/MonsterMMORPG/Wan_GGUF

**Comment by jsulz** [comment]
Thanks @FurkanGozukara 

I'm not seeing any of the files in this repository that correspond to the snippet you provided when opening the issue. Do you know what file from https://huggingface.co/MonsterMMORPG/Wan_GGUF was hanging when downloading?

Do you have any steps to reproduce this issue (specific commands invoked/code used/etc)?

**Comment by FurkanGozukara** [comment]
> Thanks [@FurkanGozukara](https://github.com/FurkanGozukara)
> 
> I'm not seeing any of the files in this repository that correspond to the snippet you provided when opening the issue. Do you know what file from https://huggingface.co/MonsterMMORPG/Wan_GGUF was hanging when downloading?
> 
> Do you have any steps to reproduce this issue (specific commands invoked/code used/etc)?

i wish i could reproduce

any chance hf_xet can provide more verbose error debug when error occurs so we can report?

**Comment by jsulz** [comment]
You can pass `RUST_LOG=info` to get `hf-xet`'s log output. If the download is happening through a Python script named `download_model.py` for example, use: 

```
RUST_LOG=info python download_model.py
```

If you're using the `huggingface-cli` or the interpreter to download, you can pass that in as well: 

```
RUST_LOG=info huggingface-cli download MonsterMMORPG/Wan_GGUF
```

Depending on the request, the output might be quite verbose so you can pipe it/copy it to a file and attach it here.

**Comment by Vagrin** [comment]
Just a heads up. I'm Windows 10, 40GB system ram, 100GB virtual memory on SSD C drive. When I use your model downloader my C drive goes to 100% and system memory almost maxes out. This turns my display into a slide show and my machine even freezes for several minutes meaning my computer is unusable for the half hour or so it may take to download one 22GB model. If I download the 22GB model directly it takes 6 minutes and my machine works fine. I think your mechanism for speeding up downloads can actually slow down the end result greatly and make the machine unusable as it downloads for some systems. It may just be my setup. But it might be older systems in general.

**Comment by FurkanGozukara** [comment]
> Just a heads up. I'm Windows 10, 40GB system ram, 100GB virtual memory on SSD C drive. When I use your model downloader my C drive goes to 100% and system memory almost maxes out. This turns my display into a slide show and my machine even freezes for several minutes meaning my computer is unusable for the half hour or so it may take to download one 22GB model. If I download the 22GB model directly it takes 6 minutes and my machine works fine. I think your mechanism for speeding up downloads can actually slow down the end result greatly and make the machine unusable as it downloads for some systems. It may just be my setup. But it might be older systems in general.

the model downloader code is this by the way



```
import sys
import subprocess
import os
import platform
import shutil
from huggingface_hub import snapshot_download
import hf_transfer

snapshot_download(
            repo_id="tencent/SongGeneration",
            local_dir=f"SongGeneration"
        )
       
```

**Comment by jsulz** [comment]
@Vagrin & @FurkanGozukara appreciate you raising this issue! 

Happy to take a look at this in a separate issue as it's not quite related to the conversation here. Before I create a new issue, when you download, do you have any `HF_XET` environment variables set (e.g., `HF_XET_HIGH_PERFORMANCE`)?

**Comment by FurkanGozukara** [comment]
> [@Vagrin](https://github.com/Vagrin) & [@FurkanGozukara](https://github.com/FurkanGozukara) appreciate you raising this issue!
> 
> Happy to take a look at this in a separate issue as it's not quite related to the conversation here. Before I create a new issue, when you download, do you have any `HF_XET` environment variables set (e.g., `HF_XET_HIGH_PERFORMANCE`)?

nope just above code and latest hf_xet

**Comment by zjsxply** [comment]
Same problem. Maybe it’s caused by unstable network connections. I found that the latest huggingface-hub uses Xet to download, which may be sensitive to network issues. I downgraded the version by running pip install "huggingface_hub<0.32" and re-ran the download command, and then the problem was solved.

**Comment by FurkanGozukara** [comment]
> Same problem. Maybe it’s caused by unstable network connections. I found that the latest huggingface-hub uses Xet to download, which may be sensitive to network issues. I downgraded the version by running pip install "huggingface_hub<0.32" and re-ran the download command, and then the problem was solved.

we really need this thing to be robust. i am using it and newbies failing to resolve issues when it fails

**Comment by jsulz** [comment]
@zjsxply would you mind providing the output of: 
* `hf env` to get more system information about the environment where you're working
* `env | grep HF_XET` 
* Reproduction steps (what repository you triggered this on, what commands/code used, etc.)

**Comment by jsulz** [comment]
> we really need this thing to be robust. i am using it and newbies failing to resolve issues when it fails

@FurkanGozukara very much agree.

**Comment by FurkanGozukara** [comment]
I am on low bandwith network and happened me as well - 14 megabit download - 0.5 megabit upload


<img width="3331" height="915" alt="Image" src="https://github.com/user-attachments/assets/bd6c99bb-f032-416c-9b33-20d3e5a8749e" />


```
(venv_downloader) E:\SwarmUI_Model_Downloader_v61\venv_downloader\Scripts>hf env

Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.34.4
- Platform: Windows-10-10.0.26100-SP0
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: C:\Users\Furkan\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers: manager
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.6
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 11.3.0
- hf_transfer: 0.1.9
- gradio: 5.35.0
- tensorboard: N/A
- numpy: 2.2.6
- pydantic: 2.11.7
- aiohttp: N/A
- hf_xet: 1.1.8
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\Furkan\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\Furkan\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\Furkan\.cache\huggingface\token
- HF_STORED_TOKENS_PATH: C:\Users\Furkan\.cache\huggingface\stored_tokens
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_DISABLE_XET: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by jsulz** [comment]
Thanks @FurkanGozukara I will try to replicate with the same settings (including network constraints). 

In a similar vein, @rajatarya is working on some tooling that can be run in tandem with downloads to aid in debugging. When that is available we'll follow up here with usage instructions.

**Comment by FurkanGozukara** [comment]
> Thanks [@FurkanGozukara](https://github.com/FurkanGozukara) I will try to replicate with the same settings (including network constraints).
> 
> In a similar vein, [@rajatarya](https://github.com/rajatarya) is working on some tooling that can be run in tandem with downloads to aid in debugging. When that is available we'll follow up here with usage instructions.

sure. because of this issue i coded a downloader :D because people keep complaining me :/

**Comment by jsulz** [comment]
Thanks for working with us on this, @FurkanGozukara 

I’ve attached two shell scripts. Use **`hf-xet-diag-windows.sh`** in a Git-Bash terminal on Windows. Use **`hf-xet-diag-linux.sh`** on Linux. The Linux script should also run under WSL, but it’s not fully tested in that environment.

### Quick start
- Make the script executable:
  ```bash
  chmod +x hf-xet-diag-windows.sh
  # or
  chmod +x hf-xet-diag-linux.sh
  ```
- Show help and options before running:
  ```bash
  ./hf-xet-diag-windows.sh -h
  # or
  ./hf-xet-diag-linux.sh -h
  ```
- If required packages are missing, the script will prompt you to install them.

### How to wrap your downloader/uploader
These scripts wrap your command so we can fetch debug symbols, capture stack traces to a local directory, and detect stalls. Practically, this means that these scripts run your upload/download scripts for you and monitor the running process.

```bash
# Example (replace with your platform’s script)
./hf-xet-diag-windows.sh -- python model_downloader.py
# or
./hf-xet-diag-linux.sh -- python model_downloader.py
```

### Output
- Each run writes diagnostics to a directory like: `diag_python_model_downloader.py_<timestamp>/`
- If you hit a hang, zip that directory and attach it here. It contains platform info and process logs only and is safe to share. Of course feel free to fully review the contents. 

I know this a somewhat unconventional way to debug this issue. However, we recognize how troublesome these issues can be and having these tools in the hands of the community can help capture actionable data when an issue occurs.

If you have any questions, feel free to ask. I will be out for the next week, but @rajatarya is available in my absence. Thank you 🤗 

[hf-xet-diag-linux.sh](https://github.com/user-attachments/files/22052876/hf-xet-diag-linux.sh)
[hf-xet-diag-windows.sh](https://github.com/user-attachments/files/22052877/hf-xet-diag-windows.sh)

**Comment by FurkanGozukara** [comment]
@jsulz thanks but here my downloader implementation which is extremely robust + fast + continues

also it checks SHA 256

perhaps it can give you idea 

i wish you had made hf xet like this

it splits into 16 pieces and downloads parallel

it has full resume feature from whever it is left

also checks SHA 256 before beginning and at the end

I had to spend huge time to figure out hf_xet download was corrupted

it was generating gibberish text with Qwen 2.5 VL but model size was perfect and there were no errors

after i manually checked sha 256 i saw mismatch

**moreover testing your commands on a low end network is so hard. it takes 10 hours to reach 99%. and i am on windows not on linux or WHL**

**i need Windows fix directly - usually cloud uses linux and they are already fast**

```
from huggingface_hub import HfApi, list_repo_files, hf_hub_url, get_hf_file_metadata
import os
import argparse
import requests
import threading
import time
import sys
import hashlib
from pathlib import Path
import concurrent.futures
from typing import List, Dict, Optional, Tuple
import shutil
import json

# Configuration
TARGET_DIR = "Qwen_Image_Training_Models"

# Precision-specific file definitions
PRECISION_FILES = {
    "bf16": [
        "qwen_2.5_vl_7b_bf16.safetensors",
        "qwen_train_vae.safetensors",
        "qwen_image_bf16.safetensors"
    ]
}

DOWNLOAD_CONFIG = {
    "repos": [
        {
            "repo_id": "MonsterMMORPG/Wan_GGUF",
            "local_dir": "Qwen_Image_Training_Models",
            "file_filters": []
        }
    ],
    "num_connections": 16,      # Fixed 16 connections
    "chunk_size": 10485760,     # 10MB buffer for streaming
    "max_retries": 5,           # Reasonable retry count
    "retry_delay": 2,           # Base delay between retries
    "max_retry_delay": 30,      # Cap exponential backoff
    "timeout": 300,             # 5 minute timeout per request
}

class RobustDownloader:
    def __init__(self, config: Dict):
        self.config = config
        # Create session with connection pooling
        self.session = requests.Session()
        adapter = requests.adapters.HTTPAdapter(
            pool_connections=20,
            pool_maxsize=20,
            max_retries=3
        )
        self.session.mount('http://', adapter)
        self.session.mount('https://', adapter)
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        })
        # SHA256 cache file
        self.sha_cache_file = "sha256_cache.json"
        self.sha_cache = self.load_sha_cache()
        
    def load_sha_cache(self) -> Dict[str, str]:
        """Load SHA256 cache from file"""
        if os.path.exists(self.sha_cache_file):
            try:
                with open(self.sha_cache_file, 'r') as f:
                    return json.load(f)
            except:
                return {}
        return {}
    
    def save_sha_cache(self):
        """Save SHA256 cache to file"""
        try:
            with open(self.sha_cache_file, 'w') as f:
                json.dump(self.sha_cache, f, indent=2)
        except Exception as e:
            print(f"Warning: Could not save SHA cache: {e}")
    
    def get_file_sha256(self, repo_id: str, filename: str) -> Optional[str]:
        """Get SHA256 hash for a file from Hugging Face"""
        cache_key = f"{repo_id}/{filename}"
        
        # Check cache first
        if cache_key in self.sha_cache:
            return self.sha_cache[cache_key]
        
        try:
            # Method 1: Try to get from file metadata
            url = hf_hub_url(repo_id, filename)
            metadata = get_hf_file_metadata(url)
            
            # The etag contains the SHA256 hash
            if hasattr(metadata, 'etag'):
                # Remove quotes and 'W/' prefix if present
                sha256 = metadata.etag.replace('"', '').replace('W/', '')
                if len(sha256) == 64:  # Valid SHA256 length
                    self.sha_cache[cache_key] = sha256
                    self.save_sha_cache()
                    return sha256
            
            # Method 2: Try API approach
            api = HfApi()
            model_info = api.model_info(repo_id, files_metadata=True)
            
            for file_info in model_info.siblings:
                if file_info.rfilename == filename:
                    if hasattr(file_info, 'lfs') and file_info.lfs:
                        sha256 = file_info.lfs.get('sha256')
                        if sha256:
                            self.sha_cache[cache_key] = sha256
                            self.save_sha_cache()
                            return sha256
            
            return None
            
        except Exception as e:
            print(f"Warning: Could not get SHA256 for {filename}: {e}")
            return None
    
    def verify_file_sha256(self, filepath: str, expected_sha: str, filename: str = "") -> bool:
        """Verify file SHA256 hash"""
        if not expected_sha:
            print(f"[WARNING] No SHA256 available for verification")
            return True  # Can't verify, assume OK
        
        print(f"[VERIFYING] Computing SHA256 for {filename or filepath}...")
        
        try:
            sha256_hash = hashlib.sha256()
            file_size = os.path.getsize(filepath)
            bytes_read = 0
            last_update = time.time()
            
            with open(filepath, "rb") as f:
                # Use 8MB chunks for better performance
                chunk_size = 8 * 1024 * 1024
                while True:
                    chunk = f.read(chunk_size)
                    if not chunk:
                        break
                    sha256_hash.update(chunk)
                    bytes_read += len(chunk)
                    
                    # Update progress
                    current_time = time.time()
                    if current_time - last_update > 1.0:
                        percent = (bytes_read / file_size) * 100
                        print(f"\r[VERIFYING] {percent:.1f}% ({self.format_bytes(bytes_read)}/{self.format_bytes(file_size)})", end='')
                        sys.stdout.flush()
                        last_update = current_time
            
            computed_sha = sha256_hash.hexdigest()
            
            if computed_sha == expected_sha:
                print(f"\r[VERIFIED] SHA256 match: {computed_sha[:16]}...")
                return True
            else:
                print(f"\r[ERROR] SHA256 mismatch!")
                print(f"  Expected: {expected_sha}")
                print(f"  Got:      {computed_sha}")
                return False
                
        except Exception as e:
            print(f"\n[ERROR] Failed to verify SHA256: {e}")
            return False
    
    def get_file_url(self, repo_id: str, filename: str) -> str:
        """Get direct download URL for HuggingFace file"""
        return f"https://huggingface.co/{repo_id}/resolve/main/{filename}"
    
    def get_file_size(self, url: str) -> Optional[int]:
        """Get file size from remote server"""
        try:
            response = self.session.head(url, timeout=30, allow_redirects=True)
            if response.status_code == 200:
                content_length = response.headers.get('content-length')
                if content_length:
                    return int(content_length)
            
            # Fallback to range request
            headers = {'Range': 'bytes=0-0'}
            response = self.session.get(url, headers=headers, timeout=30, stream=True)
            if response.status_code == 206:
                content_range = response.headers.get('content-range')
                if content_range and '/' in content_range:
                    total_size = content_range.split('/')[-1]
                    if total_size.isdigit():
                        return int(total_size)
            
            return None
        except Exception as e:
            print(f"Warning: Could not get file size: {e}")
            return None
    
    def format_bytes(self, bytes_val):
        """Format bytes to human readable format"""
        if bytes_val < 0:
            return "0 B"
        for unit in ['B', 'KB', 'MB', 'GB']:
            if bytes_val < 1024.0:
                return f"{bytes_val:.1f} {unit}"
            bytes_val /= 1024.0
        return f"{bytes_val:.1f} TB"

    def format_time(self, seconds):
        """Format seconds to human readable format"""
        if seconds < 0:
            return "0s"
        if seconds < 60:
            return f"{seconds:.0f}s"
        elif seconds < 3600:
            return f"{seconds//60:.0f}m {seconds%60:.0f}s"
        else:
            return f"{seconds//3600:.0f}h {(seconds%3600)//60:.0f}m"

    def print_progress(self, current, total, start_time, filename, speed_bytes_per_sec=None):
        """Print download progress"""
        if total <= 0:
            return
            
        elapsed = time.time() - start_time
        percent = min(100.0, (current / total * 100))
        
        # Calculate speed
        if speed_bytes_per_sec is None and elapsed > 0:
            speed_bytes_per_sec = current / elapsed
        
        # Calculate ETA
        eta_str = "Unknown"
        if speed_bytes_per_sec and speed_bytes_per_sec > 0:
            if total > current:
                eta = (total - current) / speed_bytes_per_sec
                eta_str = self.format_time(eta)
            else:
                eta_str = "Complete"
        
        # Progress bar
        bar_length = 40
        filled = int(percent * bar_length / 100)
        bar = "=" * filled + "-" * (bar_length - filled)
        
        speed_str = self.format_bytes(speed_bytes_per_sec) + "/s" if speed_bytes_per_sec else "0 B/s"
        
        sys.stdout.write(f"\r{filename}: [{bar}] {percent:.1f}% "
                        f"({self.format_bytes(current)}/{self.format_bytes(total)}) "
                        f"{speed_str} ETA: {eta_str}")
        sys.stdout.flush()
    
    def download_chunk(self, url: str, start: int, end: int, 
                      filepath: str, chunk_id: int, 
                      progress_callback=None) -> bool:
        """Download a specific chunk with resume support"""
        chunk_file = f"{filepath}.part{chunk_id}"
        chunk_size_expected = end - start + 1
        
        # Check if chunk already complete
        if os.path.exists(chunk_file):
            existing_size = os.path.getsize(chunk_file)
            if existing_size == chunk_size_expected:
                if progress_callback:
                    progress_callback(chunk_id, chunk_size_expected)
                return True
            elif existing_size > chunk_size_expected:
                # Corrupted chunk, delete and restart
                os.remove(chunk_file)
                resume_pos = 0
            else:
                # Valid partial chunk, resume
                resume_pos = existing_size
        else:
            resume_pos = 0
        
        max_retries = self.config["max_retries"]
        
        for attempt in range(max_retries):
            try:
                # Download from resume position
                actual_start = start + resume_pos
                headers = {'Range': f'bytes={actual_start}-{end}'}
                
                response = self.session.get(url, headers=headers, 
                                          timeout=self.config["timeout"], 
                                          stream=True)
                
                if response.status_code not in [200, 206]:
                    raise Exception(f"Bad status code: {response.status_code}")
                
                # Download chunk
                mode = 'ab' if resume_pos > 0 else 'wb'
                downloaded = resume_pos
                
                with open(chunk_file, mode) as f:
                    for data in response.iter_content(chunk_size=self.config["chunk_size"]):
                        if data:
                            f.write(data)
                            downloaded += len(data)
                            if progress_callback:
                                progress_callback(chunk_id, downloaded)
                
                # Verify chunk is complete
                final_size = os.path.getsize(chunk_file)
                if final_size == chunk_size_expected:
                    if progress_callback:
                        progress_callback(chunk_id, chunk_size_expected)
                    return True
                elif final_size < chunk_size_expected:
                    # Incomplete, will retry
                    resume_pos = final_size
                    raise Exception(f"Chunk incomplete: {final_size}/{chunk_size_expected}")
                else:
                    # Too large, corrupted
                    os.remove(chunk_file)
                    resume_pos = 0
                    raise Exception(f"Chunk too large: {final_size}/{chunk_size_expected}")
                    
            except Exception as e:
                if attempt < max_retries - 1:
                    delay = min(self.config["retry_delay"] * (2 ** attempt), 
                              self.config["max_retry_delay"])
                    time.sleep(delay)
                else:
                    print(f"\nChunk {chunk_id} failed after {max_retries} attempts: {e}")
                    return False
        
        return False
    
    def merge_chunks(self, filepath: str, num_chunks: int) -> bool:
        """Merge downloaded chunks into final file with optimized I/O"""
        temp_file = f"{filepath}.tmp"
        
        try:
            # Check all chunks exist and calculate total size
            total_size = 0
            chunk_files = []
            for i in range(num_chunks):
                chunk_file = f"{filepath}.part{i}"
                if not os.path.exists(chunk_file):
                    print(f"\nError: Missing chunk {i}")
                    return False
                size = os.path.getsize(chunk_file)
                chunk_files.append((chunk_file, size))
                total_size += size
            
            # For very large files (>1GB), use optimized OS-level copy
            if total_size > 1024 * 1024 * 1024:  # 1GB
                return self.merge_chunks_optimized(filepath, chunk_files, total_size, temp_file)
            
            # For smaller files, use buffered I/O
            # Use larger buffer for better I/O performance
            # 64MB buffer for optimal disk I/O
            buffer_size = 64 * 1024 * 1024
            
            # Merge to temp file with buffered I/O
            merged_size = 0
            start_time = time.time()
            last_update = time.time()
            
            with open(temp_file, 'wb') as outfile:
                for chunk_file, chunk_size in chunk_files:
                    with open(chunk_file, 'rb') as infile:
                        # Stream copy with large buffer
                        bytes_copied = 0
                        while bytes_copied < chunk_size:
                            # Read chunk in buffer-sized pieces
                            to_read = min(buffer_size, chunk_size - bytes_copied)
                            data = infile.read(to_read)
                            if not data:
                                break
                            outfile.write(data)
                            bytes_copied += len(data)
                            merged_size += len(data)
                            
                            # Update progress periodically (less frequently for better performance)
                            current_time = time.time()
                            if current_time - last_update > 1.0:  # Update every 1 second instead of 0.5
                                percent = (merged_size / total_size) * 100
                                speed = merged_size / (current_time - start_time) if current_time > start_time else 0
                                eta = (total_size - merged_size) / speed if speed > 0 else 0
                                print(f"\r[MERGING] {percent:.1f}% ({self.format_bytes(merged_size)}/{self.format_bytes(total_size)}) "
                                      f"Speed: {self.format_bytes(speed)}/s ETA: {self.format_time(eta)}", end='')
                                sys.stdout.flush()
                                last_update = current_time
            
            # Final progress
            elapsed = time.time() - start_time
            avg_speed = total_size / elapsed if elapsed > 0 else 0
            print(f"\r[MERGING] 100.0% ({self.format_bytes(total_size)}/{self.format_bytes(total_size)}) "
                  f"Completed in {self.format_time(elapsed)} - Avg: {self.format_bytes(avg_speed)}/s")
            
            # Replace target file
            if os.path.exists(filepath):
                os.remove(filepath)
            os.rename(temp_file, filepath)
            
            # Clean up chunks after successful merge
            for chunk_file, _ in chunk_files:
                try:
                    os.remove(chunk_file)
                except:
                    pass
            
            return True
            
        except Exception as e:
            print(f"\nError merging: {e}")
            if os.path.exists(temp_file):
                try:
                    os.remove(temp_file)
                except:
                    pass
            return False
    
    def merge_chunks_optimized(self, filepath: str, chunk_files: List[Tuple[str, int]], 
                               total_size: int, temp_file: str) -> bool:
        """Optimized merge for very large files using OS-level operations"""
        try:
            print(f"[MERGING] Using optimized merge for large file ({self.format_bytes(total_size)})")
            
            start_time = time.time()
            merged_size = 0
            last_update = time.time()
            
            # For Windows, use copy /b command for binary concatenation
            # For Unix, use cat command
            if sys.platform == "win32":
                # Windows: Use copy /b for binary concatenation
                with open(temp_file, 'wb') as outfile:
                    for i, (chunk_file, chunk_size) in enumerate(chunk_files):
                        print(f"\r[MERGING] Chunk {i+1}/{len(chunk_files)} ({self.format_bytes(merged_size)}/{self.format_bytes(total_size)})", end='')
                        sys.stdout.flush()
                        
                        # Use shutil.copyfileobj for better performance
                        with open(chunk_file, 'rb') as infile:
                            shutil.copyfileobj(infile, outfile, length=128*1024*1024)  # 128MB buffer
                        
                        merged_size += chunk_size
            else:
                # Unix/Linux: Use cat for concatenation
                import subprocess
                chunk_paths = [chunk_file for chunk_file, _ in chunk_files]
                
                # Build cat command
                with open(temp_file, 'wb') as outfile:
                    for chunk_file, chunk_size in chunk_files:
                        print(f"\r[MERGING] Processing {self.format_bytes(merged_size)}/{self.format_bytes(total_size)}", end='')
                        sys.stdout.flush()
                        
                        with open(chunk_file, 'rb') as infile:
                            shutil.copyfileobj(infile, outfile, length=128*1024*1024)
                        
                        merged_size += chunk_size
            
            # Final progress
            elapsed = time.time() - start_time
            avg_speed = total_size / elapsed if elapsed > 0 else 0
            print(f"\r[MERGING] 100.0% - Completed in {self.format_time(elapsed)} - Avg: {self.format_bytes(avg_speed)}/s")
            
            # Replace target file
            if os.path.exists(filepath):
                os.remove(filepath)
            os.rename(temp_file, filepath)
            
            # Clean up chunks
            for chunk_file, _ in chunk_files:
                try:
                    os.remove(chunk_file)
                except:
                    pass
            
            return True
            
        except Exception as e:
            print(f"\nError in optimized merge: {e}")
            if os.path.exists(temp_file):
                try:
                    os.remove(temp_file)
                except:
                    pass
            return False
    
    def download_file(self, repo_id: str, filename: str, local_dir: str) -> bool:
        """Main download function with SHA256 verification"""
        url = self.get_file_url(repo_id, filename)
        filepath = os.path.join(local_dir, filename)
        
        os.makedirs(local_dir, exist_ok=True)
        
        # Get expected SHA256
        expected_sha = self.get_file_sha256(repo_id, filename)
        if expected_sha:
            print(f"[INFO] Expected SHA256: {expected_sha[:16]}...")
        
        # Get file size
        file_size = self.get_file_size(url)
        
        # Check if already complete
        if os.path.exists(filepath):
            actual_size = os.path.getsize(filepath)
            if file_size:
                if actual_size == file_size:
                    # Verify SHA256 if available
                    if expected_sha:
                        if self.verify_file_sha256(filepath, expected_sha, filename):
                            print(f"[SKIP] {filename} already complete and verified ({self.format_bytes(file_size)})")
                            return True
                        else:
                            print(f"[WARNING] {filename} failed verification, re-downloading")
                            os.remove(filepath)
                    else:
                        print(f"[SKIP] {filename} already complete ({self.format_bytes(file_size)})")
                        return True
                elif actual_size > file_size:
                    print(f"[WARNING] {filename} corrupted, re-downloading")
                    os.remove(filepath)
            else:
                # Can't verify size, try SHA256 verification
                if actual_size > 1024 and expected_sha:  # > 1KB
                    if self.verify_file_sha256(filepath, expected_sha, filename):
                        print(f"[SKIP] {filename} exists and verified ({self.format_bytes(actual_size)})")
                        return True
                    else:
                        print(f"[WARNING] {filename} failed verification, re-downloading")
                        os.remove(filepath)
                elif actual_size > 1024:  # No SHA to verify
                    print(f"[SKIP] {filename} exists ({self.format_bytes(actual_size)})")
                    return True
        
        if not file_size:
            print(f"[ERROR] Cannot get size for {filename}")
            return False
        
        # Use parallel download for files > 10MB
        if file_size > 10 * 1024 * 1024:
            success = self.download_parallel(url, filepath, filename, file_size)
        else:
            success = self.download_single(url, filepath, filename, file_size)
        
        # Verify SHA256 after successful download
        if success and expected_sha:
            if not self.verify_file_sha256(filepath, expected_sha, filename):
                print(f"[ERROR] {filename} downloaded but failed SHA256 verification")
                os.remove(filepath)
                return False
        
        return success
    
    def download_parallel(self, url: str, filepath: str, filename: str, 
                         file_size: int) -> bool:
        """Download using 16 parallel connections"""
        num_chunks = self.config["num_connections"]
        
        # Calculate chunk boundaries
        base_chunk_size = file_size // num_chunks
        chunks = []
        
        for i in range(num_chunks):
            start = i * base_chunk_size
            if i == num_chunks - 1:
                # Last chunk gets all remaining bytes
                end = file_size - 1
            else:
                end = (i + 1) * base_chunk_size - 1
            chunks.append((i, start, end))
        
        print(f"[DOWNLOADING] {filename} ({self.format_bytes(file_size)}) using {num_chunks} connections")
        
        # Progress tracking
        chunk_progress = {}
        progress_lock = threading.Lock()
        
        def update_progress(chunk_id: int, bytes_downloaded: int):
            with progress_lock:
                chunk_progress[chunk_id] = bytes_downloaded
        
        # Check existing progress
        for chunk_id, start, end in chunks:
            chunk_file = f"{filepath}.part{chunk_id}"
            if os.path.exists(chunk_file):
                size = os.path.getsize(chunk_file)
                chunk_progress[chunk_id] = size
            else:
                chunk_progress[chunk_id] = 0
        
        initial_bytes = sum(chunk_progress.values())
        if initial_bytes > 0:
            print(f"[RESUMING] Already downloaded: {self.format_bytes(initial_bytes)}")
        
        # Download chunks
        start_time = time.time()
        failed_chunks = []
        
        with concurrent.futures.ThreadPoolExecutor(max_workers=num_chunks) as executor:
            # Submit all chunks
            futures = {}
            for chunk_id, start, end in chunks:
                # Only download if not complete
                chunk_file = f"{filepath}.part{chunk_id}"
                expected_size = end - start + 1
                
                if os.path.exists(chunk_file) and os.path.getsize(chunk_file) == expected_size:
                    continue  # Skip completed chunks
                
                future = executor.submit(
                    self.download_chunk,
                    url, start, end, filepath, chunk_id,
                    update_progress
                )
                futures[future] = chunk_id
            
            # If all chunks already complete
            if not futures:
                print("[MERGING] All chunks already complete")
                if self.merge_chunks(filepath, num_chunks):
                    # Verify final file
                    if os.path.getsize(filepath) == file_size:
                        print(f"[OK] {filename} completed")
                        return True
                    else:
                        print(f"[ERROR] Size mismatch after merge")
                        os.remove(filepath)
                        return False
                return False
            
            # Monitor progress
            last_update = time.time()
            last_bytes = initial_bytes
            
            while futures:
                # Wait for any future to complete
                done, pending = concurrent.futures.wait(
                    futures.keys(), 
                    timeout=0.5,
                    return_when=concurrent.futures.FIRST_COMPLETED
                )
                
                # Process completed futures
                for future in done:
                    chunk_id = futures.pop(future)
                    try:
                        success = future.result()
                        if not success:
                            failed_chunks.append(chunk_id)
                    except Exception as e:
                        print(f"\nChunk {chunk_id} exception: {e}")
                        failed_chunks.append(chunk_id)
                
                # Update progress
                current_time = time.time()
                if current_time - last_update >= 0.5 or not futures:
                    with progress_lock:
                        current_bytes = sum(chunk_progress.values())
                    
                    # Calculate speed from recent progress
                    time_delta = current_time - last_update
                    bytes_delta = current_bytes - last_bytes
                    speed = bytes_delta / time_delta if time_delta > 0 else 0
                    
                    self.print_progress(current_bytes, file_size, start_time, 
                                      filename, speed)
                    
                    last_update = current_time
                    last_bytes = current_bytes
        
        print()  # New line after progress
        
        # Check results
        if failed_chunks:
            print(f"[ERROR] Failed chunks: {failed_chunks}")
            return False
        
        # Verify all chunks are complete before merging
        for chunk_id, start, end in chunks:
            chunk_file = f"{filepath}.part{chunk_id}"
            expected_size = end - start + 1
            if not os.path.exists(chunk_file):
                print(f"[ERROR] Missing chunk {chunk_id}")
                return False
            actual_size = os.path.getsize(chunk_file)
            if actual_size != expected_size:
                print(f"[ERROR] Chunk {chunk_id} incomplete: {actual_size}/{expected_size}")
                return False
        
        # Merge chunks
        print(f"[MERGING] Merging {num_chunks} chunks...")
        if self.merge_chunks(filepath, num_chunks):
            # Verify final file size
            final_size = os.path.getsize(filepath)
            if final_size == file_size:
                elapsed = time.time() - start_time
                avg_speed = (file_size - initial_bytes) / elapsed if elapsed > 0 else 0
                print(f"[OK] {filename} completed in {self.format_time(elapsed)} "
                      f"- Average: {self.format_bytes(avg_speed)}/s")
                return True
            else:
                print(f"[ERROR] Final size mismatch: {final_size} != {file_size}")
                os.remove(filepath)
                return False
        else:
            print(f"[ERROR] Merge failed")
            return False
    
    def download_single(self, url: str, filepath: str, filename: str, 
                       file_size: int) -> bool:
        """Single connection download for small files"""
        max_retries = self.config["max_retries"]
        
        for attempt in range(max_retries):
            try:
                # Check existing file
                resume_pos = 0
                if os.path.exists(filepath):
                    resume_pos = os.path.getsize(filepath)
                    if resume_pos >= file_size:
                        print(f"[OK] {filename} already complete")
                        return True
                
                # Download
                headers = {'Range': f'bytes={resume_pos}-'} if resume_pos > 0 else {}
                response = self.session.get(url, headers=headers, 
                                          timeout=self.config["timeout"], 
                                          stream=True)
                
                if resume_pos > 0 and response.status_code != 206:
                    print(f"[WARNING] Resume not supported, restarting")
                    resume_pos = 0
                    response = self.session.get(url, timeout=self.config["timeout"], 
                                              stream=True)
                
                response.raise_for_status()
                
                # Write file
                mode = 'ab' if resume_pos > 0 else 'wb'
                downloaded = 0
                start_time = time.time()
                
                if resume_pos > 0:
                    print(f"[RESUMING] {filename} from {self.format_bytes(resume_pos)}")
                else:
                    print(f"[DOWNLOADING] {filename} ({self.format_bytes(file_size)})")
                
                with open(filepath, mode) as f:
                    for chunk in response.iter_content(chunk_size=self.config["chunk_size"]):
                        if chunk:
                            f.write(chunk)
                            downloaded += len(chunk)
                            
                            # Progress update
                            if time.time() - start_time > 0.5:
                                total = resume_pos + downloaded
                                self.print_progress(total, file_size, start_time, filename)
                
                # Final progress
                total = resume_pos + downloaded
                self.print_progress(total, file_size, start_time, filename)
                print()
                
                # Verify
                if os.path.getsize(filepath) == file_size:
                    print(f"[OK] {filename} completed")
                    return True
                else:
                    print(f"[ERROR] Size mismatch")
                    continue
                    
            except Exception as e:
                print(f"\n[ERROR] Attempt {attempt + 1}: {e}")
                if attempt < max_retries - 1:
                    delay = min(self.config["retry_delay"] * (2 ** attempt), 
                              self.config["max_retry_delay"])
                    time.sleep(delay)
                else:
                    return False
        
        return False

def scan_repo_files(repo_id: str, specific_files: List[str] = None) -> List[str]:
    """Get list of files to download"""
    try:
        if specific_files:
            print(f"Using predefined file list")
            return specific_files
        
        api = HfApi()
        all_files = list_repo_files(repo_id=repo_id, repo_type="model")
        return all_files
        
    except Exception as e:
        print(f"Error scanning repository: {e}")
        return specific_files if specific_files else []

def get_precision_choice():
    """Get precision choice from user - BF16 only"""
    # Since we only have BF16 now, directly return it
    print("\nDownloading BF16 models...")
    return "bf16"

def download_models(precision: Optional[str] = None, download_dir: Optional[str] = None):
    """Main download function"""
    # Always use BF16 since FP8 is no longer needed
    if not precision or precision not in ["bf16"]:
        precision = "bf16"
    
    target_dir = download_dir if download_dir else TARGET_DIR
    
    # Get file list - only BF16 available now
    files_to_download = PRECISION_FILES["bf16"]
    print(f"\nDownloading BF16 models...")
    
    downloader = RobustDownloader(DOWNLOAD_CONFIG)
    
    os.makedirs(target_dir, exist_ok=True)
    
    for repo_config in DOWNLOAD_CONFIG["repos"]:
        repo_id = repo_config["repo_id"]
        
        print(f"\nRepository: {repo_id}")
        print(f"Target: {os.path.abspath(target_dir)}")
        
        files = scan_repo_files(repo_id, files_to_download)
        
        if not files:
            print("No files found")
            continue
        
        # Check existing files with SHA256 verification
        to_download = []
        skipped = []
        
        for filename in files:
            filepath = os.path.join(target_dir, filename)
            if os.path.exists(filepath) and os.path.getsize(filepath) > 1024:
                # Try to verify with SHA256
                expected_sha = downloader.get_file_sha256(repo_id, filename)
                if expected_sha:
                    if downloader.verify_file_sha256(filepath, expected_sha, filename):
                        skipped.append(filename)
                    else:
                        print(f"[RE-DOWNLOAD] {filename} failed verification")
                        to_download.append(filename)
                else:
                    # No SHA available, skip if file exists
                    skipped.append(filename)
            else:
                to_download.append(filename)
        
        print(f"\nTotal files: {len(files)}")
        if skipped:
            print(f"Already downloaded: {len(skipped)}")
            for f in skipped:
                print(f"  ✓ {f}")
        
        if not to_download:
            print("All files already downloaded!")
            continue
        
        print(f"To download: {len(to_download)}")
        
        # Download files
        successful = 0
        failed = 0
        
        for i, filename in enumerate(to_download, 1):
            print(f"\n[{i}/{len(to_download)}]")
            if downloader.download_file(repo_id, filename, target_dir):
                successful += 1
            else:
                failed += 1
                print(f"[FAILED] {filename}")
        
        # Summary
        print(f"\n{'='*50}")
        print(f"Summary:")
        print(f"  Already had: {len(skipped)}")
        print(f"  Downloaded: {successful}")
        print(f"  Failed: {failed}")
    
    print(f"\n{'='*50}")
    print(f"Downloads complete!")
    print(f"Location: {os.path.abspath(target_dir)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Download Qwen models')
    parser.add_argument('--precision', choices=['bf16'], 
                       help='Model precision (only bf16 available)')
    parser.add_argument('--dir', type=str, 
                       help='Download directory')
    
    args = parser.parse_args()
    download_models(args.precision, args.dir)
```

**Comment by atagunov** [comment]
Happens all the time to me on datacrunch.. so upsetting :(

/path-to-my/venv/bin/hf download Comfy-Org/Wan_2.2_ComfyUI_Repackaged \
  split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp16.safetensors \
  --local-dir /mnt/nvme/ComfyUI/models/diffusion_models \
  --max-workers 16

**Comment by kayingai** [comment]
WARN  Retry attempt #0. Sleeping 1.8750456s before the next attempt
    at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\reqwest-retry-0.7.0\src\middleware.rs:171

**Comment by jsulz** [comment]
@FurkanGozukara  - thanks for the feedback on the diagnostic scripts; completely understand the annoyance in retesting these downloads on a slow network. At the moment, without directly adding telemetry to the package, however, these have proven helpful while we've debugged other user issues. We are continuing to invest in these and [have released more across a range of platforms](https://github.com/huggingface/xet-core?tab=readme-ov-file#issues-diagnostics--debugging). 

Concerning the downloads themselves, I appreciate you sharing your download script. For `hf-xet` it's definitely a balance between speed and consistency. In general, we've tried to achieve a wide range of interoperability with different platforms and work in different environments, but I agree that reliability in network constrained environments is an area of improvement. It's something that we will address and feedback from you/the broader community is helpful on that front. 

Looking through this thread, I don't believe that I've explicitly noted that there is a flag to disable `hf-xet` in the case that a download is proving particularly troublesome - [it's documented here](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubdisablexet). This will push download requests to a component of our architecture - [the Git LFS bridge](https://huggingface.co/docs/hub/storage-backends#backward-compatibility-with-lfs) - that does the work of reconstructing the file chunks for the client. Your download script, by requesting the file from a single HTTP endpoint, already relies on this part of our system. Using the `HF_HUB_DISABLE_XET` might be easier in some cases rather than a separate download script. 

@atagunov thanks for your report! Could you provide the output of `hf env` so that we have more information about your environment?

@wordsvideo-dev those messages are valid retries and the download should continue past them. If that's not the case, providing an output of `hf env`, what repository you are interacting with, and what commands you are using to download would be helpful. Thank you!

**Comment by FurkanGozukara** [comment]
@jsulz any chance you can also add hash check? recently i had a model accurate file size, not causing error but causing broken output

it turns out hash was not accurate

now i improved my downloader to this to handle all :D https://gist.github.com/FurkanGozukara/79ea8b887f5956e152b419d5d4164152

it works insanely good

**Comment by jsulz** [comment]
@FurkanGozukara that would likely be implemented from within a higher-level client (e.g., `huggingface_hub` or `huggingface.js`) so that the feature was transparent and configurable to users who may not want or need such a check. You can actually see some discussion of this happening within a few issues on `huggingface_hub`:

- https://github.com/huggingface/huggingface_hub/issues/2364
- https://github.com/huggingface/huggingface_hub/issues/3298

If this is something you would like, I would check out and comment there. There is also a good summary of why it's important to consider this deeply and what the issues are with adding it here: https://github.com/huggingface/huggingface_hub/issues/2364#issuecomment-2202703368 

Could you provide more details about how you encountered this issue? What repo, what commands you ran, what environment (operating system, etc), and whether you encountered it consistently? I'm curious to know more about how exactly this happened.

**Comment by FurkanGozukara** [comment]
> [@FurkanGozukara](https://github.com/FurkanGozukara) that would likely be implemented from within a higher-level client (e.g., `hugginface_hub` or `hugginface.js`) so that the feature was transparent and configurable to users who may not want or need such a check. You can actually see some discussion of this happening within a few issues on `hugginface_hub`:
> 
> * [Checksum validation with hf_hub_download on model files. huggingface_hub#2364](https://github.com/huggingface/huggingface_hub/issues/2364)
> * [command for verifying local files huggingface_hub#3298](https://github.com/huggingface/huggingface_hub/issues/3298)
> 
> If this is something you would like, I would check out and comment there. There is also a good summary of why it's important to consider this deeply and what the issues are with adding it here: [huggingface/huggingface_hub#2364 (comment)](https://github.com/huggingface/huggingface_hub/issues/2364#issuecomment-2202703368)
> 
> Could you provide more details about how you encountered this issue? What repo, what commands you ran, what environment (operating system, etc), and whether you encountered it consistently? I'm curious to know more about how exactly this happened.

it was hf_xet download 

this is certainly not a consistent isssue and mostly happens at lower connection speed enviroments 

here even i made an issue thread

https://github.com/kohya-ss/musubi-tuner/issues/512

Qwen2.5-VL was generating gibberish text

repo is here : MonsterMMORPG/Wan_GGUF

downloaded model is : qwen_2.5_vl_7b_bf16.safetensors

when you read the thread you will see more details

**Comment by rajatarya** [comment]
> > [@FurkanGozukara](https://github.com/FurkanGozukara) that would likely be implemented from within a higher-level client (e.g., `hugginface_hub` or `hugginface.js`) so that the feature was transparent and configurable to users who may not want or need such a check. You can actually see some discussion of this happening within a few issues on `hugginface_hub`:
> > 
> > * [Checksum validation with hf_hub_download on model files. huggingface_hub#2364](https://github.com/huggingface/huggingface_hub/issues/2364)
> > * [command for verifying local files huggingface_hub#3298](https://github.com/huggingface/huggingface_hub/issues/3298)
> > 
> > If this is something you would like, I would check out and comment there. There is also a good summary of why it's important to consider this deeply and what the issues are with adding it here: [huggingface/huggingface_hub#2364 (comment)](https://github.com/huggingface/huggingface_hub/issues/2364#issuecomment-2202703368)
> > Could you provide more details about how you encountered this issue? What repo, what commands you ran, what environment (operating system, etc), and whether you encountered it consistently? I'm curious to know more about how exactly this happened.
> 
> it was hf_xet download
> 
> this is certainly not a consistent isssue and mostly happens at lower connection speed enviroments
> 
> here even i made an issue thread
> 
> [kohya-ss/musubi-tuner#512](https://github.com/kohya-ss/musubi-tuner/issues/512)
> 
> Qwen2.5-VL was generating gibberish text
> 
> repo is here : MonsterMMORPG/Wan_GGUF
> 
> downloaded model is : qwen_2.5_vl_7b_bf16.safetensors
> 
> when you read the thread you will see more details

@FurkanGozukara I looked through the thread and noticed that on Windows `hf-xet` was not in the `pip freeze` output. Are you sure `hf-xet` was involved in the download on Windows?

**Comment by FurkanGozukara** [comment]
@rajatarya yes i used seperate downloader app that installed hf_xet

it was installing into global python

**Comment by rajatarya** [comment]
Quick follow up here @FurkanGozukara @atagunov @zjsxply : We released `hf-xet 1.2.0` on Friday and it disables using the xet disk cache (chunk_cache) by default. From our testing we found this was negatively impacting download performance (especially on Windows) without much benefit (the main benefit of the chunk cache is when editing files in a repo). We've also introduced a better and more robust logging system in `hf-xet 1.2.0`. Can you retry downloading models using `hf-xet, pip install -U huggingface_hub hf_xet` and report back if things are working?

btw `huggingface-hub 1.0` now depends on `hf-xet 1.2.0` so by updating to the latest `huggingface-hub` you should get `hf-xet` updated as well.

**Comment by FurkanGozukara** [comment]
@rajatarya amazing news. sadly i dont have slower internet right now to test

**Comment by xyang2013** [comment]
I am still having the download issue with hf-xet 1.2.0. It kept on getting stucks.

**Comment by rajatarya** [comment]
@xyang2013 Sorry to hear that. @hoytak is working on changes to make the concurrency used adaptive so we can lower the defaults in `hf-xet` and not saturate the network environment. Stay tuned for that to ship soon!

**Comment by rajatarya** [comment]
@xyang2013 @FurkanGozukara, @atagunov @zjsxply : We have shipped hf-xet 1.3.0 with Adaptive Concurrency, which from our testing, we believe fix the issues you experienced. Thank you for your patience with us fixing this. Please update to the latest hf-xet to see adaptive concurrency in action.

Adaptive Concurrency is a big change to how hf-xet uploads and downloads files. With it, hf-xet will automatically (and in real-time) monitor system resources to ensure that they are getting utilized appropriately. Previously the default resources used were greater than available and without manual tuning the experience with hf-xet could be suboptimal (as you reported). Now, with adaptive concurrency, hf-xet will increase connections and segment sizes to maximize available resources. If the available resources go down then hf-xet will reduce the concurrency used. In this way, from extensive testing, we've seen hf-xet now be able to correctly adapt to minimal resource environments (ex. laptop on flaky wifi + slow disk) and maximal environments (cloud machine with 10G network and nvme disk).

**Comment by FurkanGozukara** [comment]
> [@xyang2013](https://github.com/xyang2013) [@FurkanGozukara](https://github.com/FurkanGozukara), [@atagunov](https://github.com/atagunov) [@zjsxply](https://github.com/zjsxply) : We have shipped hf-xet 1.3.0 with Adaptive Concurrency, which from our testing, we believe fix the issues you experienced. Thank you for your patience with us fixing this. Please update to the latest hf-xet to see adaptive concurrency in action.
> 
> Adaptive Concurrency is a big change to how hf-xet uploads and downloads files. With it, hf-xet will automatically (and in real-time) monitor system resources to ensure that they are getting utilized appropriately. Previously the default resources used were greater than available and without manual tuning the experience with hf-xet could be suboptimal (as you reported). Now, with adaptive concurrency, hf-xet will increase connections and segment sizes to maximize available resources. If the available resources go down then hf-xet will reduce the concurrency used. In this way, from extensive testing, we've seen hf-xet now be able to correctly adapt to minimal resource environments (ex. laptop on flaky wifi + slow disk) and maximal environments (cloud machine with 10G network and nvme disk).

awesome thanks

is it auto or you set some parameter?

**Comment by rajatarya** [comment]
@FurkanGozukara : it is automatically used with `hf-xet >= 1.3.0`. No longer need to use HIGH_PERFORMANCE=1 either, just use the latest hf-xet and adaptive concurrency is enabled by default.
