### ISSUE TITLE
Bug: Python exception updating progress - (Pin `ipykernel < 7.0.0`)

### ISSUE THREAD

**Issue by achembarpu** [huggingface/xet-core#526]
### Describe the bug

Hi team,

I appear to be facing an error stemming from the progress update side of things - that breaks model download. Maybe there's some version mismatch with jupyter widgets? I'm using the latest versions of all packages (see below).

Do let me know what extra info you need. Thanks!

### Reproduction

```python
from unsloth import FastVisionModel
import torch
from transformers import TextStreamer

model, tokenizer = FastVisionModel.from_pretrained(
    "unsloth/Qwen2.5-VL-7B-Instruct-bnb-4bit",
    load_in_4bit=True,  # Use 4bit to reduce memory use. False for 16bit LoRA.
    use_gradient_checkpointing="unsloth",  # True or "unsloth" for long context
)
```

```txt
pillow==11.3.0
numpy==2.3.3
unsloth==2025.10.1
jupyter==1.1.1
unsloth-zoo==2025.10.1
```

### Logs

```shell
==((====))==  Unsloth 2025.10.1: Fast Qwen2_5_Vl patching. Transformers: 4.56.2.
   \\   /|    NVIDIA GeForce RTX 3080. Num GPUs = 1. Max memory: 9.631 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu128. CUDA: 8.6. CUDA Toolkit: 12.8. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
model.safetensors:   0%
 0.00/6.90G [00:00<?, ?B/s]
  2025-10-13T20:37:33.028737Z ERROR  Python exception updating progress:, error: PyErr { type: <class 'LookupError'>, value: LookupError(<ContextVar name='shell_parent' at 0x7535b4cebd80>), traceback: Some(<traceback object at 0x753408489f40>) }, caller: "src/progress_update.rs:313"
    at /home/runner/work/xet-core/xet-core/error_printer/src/lib.rs:28
```

### System info

```shell
- huggingface_hub version: 0.35.3
- Platform: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
- Python version: 3.12.11
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /home/achembarpu/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.8.0
- Jinja2: 3.1.6
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 11.3.0
- hf_transfer: 0.1.9
- gradio: N/A
- tensorboard: N/A
- numpy: 2.3.3
- pydantic: N/A
- aiohttp: 3.13.0
- hf_xet: 1.1.10
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: ./huggingface_cache
- HF_ASSETS_CACHE: /home/achembarpu/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/achembarpu/.cache/huggingface/token
- HF_STORED_TOKENS_PATH: /home/achembarpu/.cache/huggingface/stored_tokens
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_DISABLE_XET: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10

HF_XET_HIGH_PERFORMANCE=1
HF_XET_CHUNK_CACHE_SIZE_BYTES=0
HF_XET_RECONSTRUCT_WRITE_SEQUENTIALLY=0
HF_XET_NUM_CONCURRENT_RANGE_GETS=64
```

**Comment by danielhanchen** [comment]
It seems like https://pypi.org/project/ipykernel/#history update yesterday and it's causing issues sadly - downgrading to `"ipykernel==6.30.1"` should work - I'm adding a check inside of Unsloth as well to warn about the issue

**Comment by jsulz** [comment]
Thanks @danielhanchen! This does indeed look related to an issue with ipykernel (likely https://github.com/ipython/ipykernel/issues/1450). 

It looks like the team there is working on this, in the meantime, pinning ipykernel to the last stable version prior to `7.0.0` (https://github.com/ipython/ipykernel/releases/tag/v6.30.1) like @danielhanchen notes will address the issue. 

Since this is not strictly an `hf-xet` issue, I'm going to close this for now.

**Comment by lgautier** [comment]
> It seems like https://pypi.org/project/ipykernel/#history update yesterday and it's causing issues sadly - downgrading to `"ipykernel==6.30.1"` should work - I'm adding a check inside of Unsloth as well to warn about the issue

When downgrading ipykernel to 6.30.1 the error LOG message is gone, but the time to download and download rate do not seem to update (even after the download is complete).

**Comment by steveepreston** [comment]
I don't want to downgrade `ipykernel` as facing issues.
is there a way to downgrade/turnoff/remove `hf_xet`?

**Comment by jsulz** [comment]
Reopening this and reframing it a bit so it's more clear and visible to the community what is happening and what the short-term remediation is. Will close it after the release of the next `ipykernel` that addresses this. 

@lgautier - I can't reproduce your experience either on `ipykernel==6.30.1` or on `main` of the package. Could you share your environment details with `hf env` and a small reproducible example of how you're encountering this?

@steveepreston you can temporarily disable hf-xet[ with this environment variable](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubdisablexet) or uninstall the package from your Python environment. However, it does look like the work on https://github.com/ipython/ipykernel/issues/1450 resolves this issue and so a release from the `ipykernel` team should address the core problem. You can test this yourself by building the package from main - `pip install "ipykernel @ git+https://github.com/ipython/ipykernel@main"`

**Comment by steveepreston** [comment]
> you can temporarily disable hf-xet with this environment variable

Thanks, what is the name?

**Comment by jsulz** [comment]
@steveepreston apologies, updated my comment with a link to the docs page for it.

**Comment by lgautier** [comment]
(...)
> 
> [@lgautier](https://github.com/lgautier) - I can't reproduce your experience either on `ipkernel==6.30.1` or on `main` of the package. Could you share your environment details with `hf env` and a small reproducible example of how you're encountering this?

I no longer have the virtualenv and I can no longer reproduce the issue myself either after trying recreate one.
Not sure about what happened. May be there is was a temporary dependency glitch after I downgraded to `ipykernel==6.30.1` with pip.

**Comment by steveepreston** [comment]
> apologies, updated my comment with a link to the docs page for it.

No problem! Thanks.
Strange thing is i already set `os.environ["HF_HUB_DISABLE_XET"] = "1"` at the beginning of my code!

**Comment by jsulz** [comment]
Closing this issue as it's now resolved as of the latest release of `ipykernel`!

@steveepreston sorry I missed your last comment concerning disabling `hf-xet` already with that environment variable. If you find that flag isn't working inside a notebook or another environment, feel free to open an issue with more information (environment info, reproducible code, etc). In my own testing in a local notebook I've been able to set it successfully, but it might be a problem elsewhere!

**Comment by steveepreston** [comment]
@jsulz Thanks! ok

**Comment by danielhanchen** [comment]
As a follow up `ipykernel>=7.1.0` does partially solve most issues, but in some super rare cases according to people, it still doesn't work (very rare like I saw 1 case)

**Comment by jsulz** [comment]
@danielhanchen curious! I haven't been able to reproduce this on my end. Happy to look into it - would it be possible to open up a new issue with details?
